### ISSUE TITLE
How to solve the error of AssertionError: The environment must specify an action space

### ISSUE THREAD

**Issue by yasamin62** [zhangzhizza/Gym-Eplus#8]
Hi

I have installed successfully the eplus-env-0.0.1.
In fact, I have done the following lines in the Windows command prompt:

cd C:\0-Yasamin\...\Gym-Eplus-master
git clone https://github.com/zhangzhizza/Gym-Eplus.git
cd Gym-Eplus

python -m venv .env
.env\Scripts\activate

pip install gym
pip install -e .

then I typed "python" in cmd and continue with:

>>> import gym
>>> import eplus_env;
>>> env = gym.make('Eplus-demo-v1');

but when I used the example and type the " env = gym.make('Eplus-demo-v1');" in the Windows command prompt, it gives this error.

>>> env = gym.make('Eplus-demo-v1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\0-Yasamin\...\Gym-Eplus-master\Gym-Eplus\.env\lib\site-packages\gym\envs\registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "C:\0-Yasamin\...\Gym-Eplus-master\Gym-Eplus\.env\lib\site-packages\gym\wrappers\env_checker.py", line 20, in __init__
    assert hasattr(
AssertionError: The environment must specify an action space. https://www.gymlibrary.dev/content/environment_creation/
>>>

I am a beginner with python and OpenAI gym, Could you please guide me to correct it?
Thanks

**Comment by yasamin62** [comment]
@asrjy @zhangzhizza

**Comment by Songshilongi** [comment]
I also want konw

**Comment by asrjy** [comment]
@yasamin62 @Songshilongi ensure you're using gym version 0.19

**Comment by zhangzhizza** [comment]
Hi,

Sorry for the delayed response. The package is quite outdated, I am currently using FMI to wrap up EnergyPlus for Python interface. That may be better for this package. 

Best
Zhiang

**Comment by Songshilongi** [comment]
@asrjy I have sloved it, I forgrt 'isopen = true'

**Comment by ozanbarism** [comment]
Can anyone clarify how they solved this issue? i am still facing the same problem.
